services:
  db:
    image: mysql:8.2.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: aturapp
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - 3306:3306
    volumes:
      - ./back/mysql_data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 9090:8080

  laravel:
    build: ./back/laravel
    ports:
      - 8000:8000
    volumes:
      - ./back/laravel:/var/www/
    working_dir: /var/www/
    depends_on:
      - db
    command: ["bash", "-c", "/var/www/script.sh"]

  node:
    image: node
    restart: always
    depends_on:
      - db
    ports:
      - 8001:8001
    volumes:
      - ./back/node:/home/node/app
    working_dir: /home/node/app
    command: bash -c "npm i && cp npm start"

  vue:
    build: ./front