  services:
    db:
      image: mysql:8.2.0
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: aturapp
        MYSQL_USER: user
        MYSQL_PASSWORD: user
      ports:
        - 3306:3306
      volumes:
        - ./back/mysql_data:/var/lib/mysql
      command: --host_cache_size=0

    adminer:
      image: adminer
      restart: always
      depends_on:
        - db
      ports:
        - 9090:8080

    laravel:
      build: ./back/laravel
      ports:
        - 9000:8000
      volumes:
        - ./back/laravel:/var/www/html
      working_dir: /var/www/html
      depends_on:
        - db
      command: ["bash", "-c", "/var/www/html/script.sh"]

    node:
      image: node
      restart: always
      depends_on:
        - db
      ports:
        - 8001:8001
      volumes:
        - ./back/node:/home/node/app
        - /home/node/app/node_modules
      working_dir: /home/node/app
      command: bash -c "npm i && npm start"

    vue:
      build: ./front
      ports:
        - 8000:5173
      volumes:
        - ./front:/app
        - /app/node_modules
      working_dir: /app/
      # depends_on: //no quiero que si laravel no va, la pagina no vaya
      #   - laravel
        # - node
      command: bash -c "npm install && npm run dev -- --host 0.0.0.0"
      