<?php

namespace Database\Seeders;

use App\Models\Sector;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SectorsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('sectors')->insert([
            ['sector' => 'edifici', 'planta_id' => 1],
            ['sector' => 'gimnas', 'planta_id' => 1],
            ['sector' => 'pati-eso-1', 'planta_id' => 1],
            ['sector' => 'camp-futbol-sala', 'planta_id' => 1],
            ['sector' => 'parquing', 'planta_id' => 1],
            ['sector' => 'taules-ping-pong', 'planta_id' => 1],
            ['sector' => 'entrada', 'planta_id' => 1],
            ['sector' => 'entrada-cantina', 'planta_id' => 1],
            ['sector' => 'entrada-cotxe', 'planta_id' => 1],
            ['sector' => 'escales-pati', 'planta_id' => 1],
            ['sector' => 'picnic', 'planta_id' => 1],
            ['sector' => 'camp-futbol', 'planta_id' => 1],
            ['sector' => 'pista-basquet', 'planta_id' => 1],
            ['sector' => 'pati-eso-2', 'planta_id' => 1],
            ['sector' => 'wc0', 'planta_id' => 2],
            ['sector' => 'ala-ausias0', 'planta_id' => 2],
            ['sector' => 'pasillo-ausias0', 'planta_id' => 2],
            ['sector' => 'ala-bosca0', 'planta_id' => 2],
            ['sector' => 'pasillo-bosca0', 'planta_id' => 2],
            ['sector' => 'pb-13', 'planta_id' => 2],
            ['sector' => 'pb-11', 'planta_id' => 2],
            ['sector' => 'pb-12', 'planta_id' => 2],
            ['sector' => 'pb-14', 'planta_id' => 2],
            ['sector' => 'pb-10', 'planta_id' => 2],
            ['sector' => 'fin-ala-ausias0', 'planta_id' => 2],
            ['sector' => 'pb-01', 'planta_id' => 2],
            ['sector' => 'pb-03', 'planta_id' => 2],
            ['sector' => 'pb-05', 'planta_id' => 2],
            ['sector' => 'pb-04', 'planta_id' => 2],
            ['sector' => 'pb-06', 'planta_id' => 2],
            ['sector' => 'pb-07', 'planta_id' => 2],
            ['sector' => 'pb-09', 'planta_id' => 2],
            ['sector' => 'pb-02', 'planta_id' => 2],
            ['sector' => 'pb-08', 'planta_id' => 2],
            ['sector' => 'fin-ala-bosca0', 'planta_id' => 2],
            ['sector' => 'ala-ausias1', 'planta_id' => 3],
            ['sector' => 'pasillo-ausias1', 'planta_id' => 3],
            ['sector' => 'sem-castella-ausias1', 'planta_id' => 3],
            ['sector' => 'p1-inf5', 'planta_id' => 3],
            ['sector' => 'p1-09', 'planta_id' => 3],
            ['sector' => 'p1-inf3', 'planta_id' => 3],
            ['sector' => 'p1-inf2', 'planta_id' => 3],
            ['sector' => 'p1-inf1', 'planta_id' => 3],
            ['sector' => 'p1-08', 'planta_id' => 3],
            ['sector' => 'p1-inf4', 'planta_id' => 3],
            ['sector' => 'sala-multifuncional-2', 'planta_id' => 3],
            ['sector' => 'fin-ala-ausias1', 'planta_id' => 3],
            ['sector' => 'ala-bosca1', 'planta_id' => 3],
            ['sector' => 'pasillo-bosca1', 'planta_id' => 3],
            ['sector' => 'sem-castella-bosca1', 'planta_id' => 3],
            ['sector' => 'p1-01', 'planta_id' => 3],
            ['sector' => 'p1-03', 'planta_id' => 3],
            ['sector' => 'p1-04', 'planta_id' => 3],
            ['sector' => 'p1-06', 'planta_id' => 3],
            ['sector' => 'p1-07', 'planta_id' => 3],
            ['sector' => 'p1-02', 'planta_id' => 3],
            ['sector' => 'biblioteca', 'planta_id' => 3],
            ['sector' => 'p1-05', 'planta_id' => 3],
            ['sector' => 'fin-ala-bosca1', 'planta_id' => 3],
            ['sector' => 'lavabo-homes2', 'planta_id' => 4],
            ['sector' => 'ala-ausias2', 'planta_id' => 4],
            ['sector' => 'laboratori-fisica-2', 'planta_id' => 4],
            ['sector' => 'laboratori-quimica-2', 'planta_id' => 4],
            ['sector' => 'pasillo-ausias2', 'planta_id' => 4],
            ['sector' => 'p2-inf6', 'planta_id' => 4],
            ['sector' => 'p2-09', 'planta_id' => 4],
            ['sector' => 'p2-10', 'planta_id' => 4],
            ['sector' => 'p2-11', 'planta_id' => 4],
            ['sector' => 'p2-08', 'planta_id' => 4],
            ['sector' => 'p2-07', 'planta_id' => 4],
            ['sector' => 'fin-ala-ausias2', 'planta_id' => 4],
            ['sector' => 'wc2', 'planta_id' => 4],
            ['sector' => 'ala-bosca2', 'planta_id' => 4],
            ['sector' => 'laboratori-quimica-1', 'planta_id' => 4],
            ['sector' => 'laboratori-fisica-1', 'planta_id' => 4],
            ['sector' => 'pasillo-bosca2', 'planta_id' => 4],
            ['sector' => 'p2-01', 'planta_id' => 4],
            ['sector' => 'p2-03', 'planta_id' => 4],
            ['sector' => 'p2-04', 'planta_id' => 4],
            ['sector' => 'p2-02', 'planta_id' => 4],
            ['sector' => 'p2-05', 'planta_id' => 4],
            ['sector' => 'p2-06', 'planta_id' => 4],
            ['sector' => 'fin-ala-bosca2', 'planta_id' => 4],
            ['sector' => 'lavabo-alumnat', 'planta_id' => 5],
            ['sector' => 'lavabo-dones', 'planta_id' => 5],
            ['sector' => 'ala-ausias', 'planta_id' => 5],
            ['sector' => 'ala-bosca', 'planta_id' => 5],
            ['sector' => 'dept-catala', 'planta_id' => 5],
            ['sector' => 'dept-matematiques', 'planta_id' => 5],
            ['sector' => 'p3-inf9', 'planta_id' => 5],
            ['sector' => 'pasillo-ausias', 'planta_id' => 5],
            ['sector' => 'p3-inf7', 'planta_id' => 5],
            ['sector' => 'p3-08', 'planta_id' => 5],
            ['sector' => 'p3-06', 'planta_id' => 5],
            ['sector' => 'p3-04', 'planta_id' => 5],
            ['sector' => 'lab-ciencies-naturals', 'planta_id' => 5],
            ['sector' => 'dept-ciencies-naturals', 'planta_id' => 5],
            ['sector' => 'pasillo-bosca', 'planta_id' => 5],
            ['sector' => 'p3-01', 'planta_id' => 5],
            ['sector' => 'p3-02', 'planta_id' => 5],
            ['sector' => 'p3-03', 'planta_id' => 5],
            ['sector' => 'p3-05', 'planta_id' => 5],
            ['sector' => 'p3-07', 'planta_id' => 5],
            ['sector' => 'lab-ciencies-naturals-2', 'planta_id' => 5],
            ['sector' => 'p3-inf11', 'planta_id' => 5],
            ['sector' => 'p3-inf10', 'planta_id' => 5],
            ['sector' => 'dept-ll-estrangeres', 'planta_id' => 5],
            ['sector' => 'dept-tecnologia', 'planta_id' => 5],
            ['sector' => 'p3-inf3', 'planta_id' => 5],
            ['sector' => 'fin-ala-bosca', 'planta_id' => 5],
            ['sector' => 'fin-ala-ausias', 'planta_id' => 5],
        ]);
    }
}